import { EffectMapping } from "@shared/schema";

export const effectsMapping: EffectMapping[] = [
  { friendly: "10 Band Graphic", internal: "HD2_EQGraphic10Band" },
  { friendly: "12-String", internal: "VIC_PitchTwelveString" },
  { friendly: "3 Note Generator", internal: "HD2_Synth3NoteGenerator" },
  { friendly: "3-Band Comp", internal: "HD2_Compressor3BandComp" },
  { friendly: "4 OSC Generator", internal: "HD2_Synth4OSCGenerator" },
  { friendly: "4-Voice Chorus", internal: "HD2_Chorus4Voice" },
  { friendly: "60s Bias Trem", internal: "HD2_Tremolo60sBiasTrem" },
  { friendly: "70s Chorus", internal: "HD2_Chorus70sChorus" },
  { friendly: "ADT", internal: "HD2_DelayADT" },
  { friendly: "AM Ring Mod", internal: "HD2_RingModulatorAMRingMod" },
  { friendly: "Acoustic Sim", internal: "L6SPB_AcousGtrSim" },
  { friendly: "Adriatic Delay", internal: "HD2_DelayAdriaticDelay" },
  { friendly: "Adriatic Swell", internal: "HD2_DelaySwellAdriatic" },
  { friendly: "Alpaca Rouge", internal: "HD2_DistAlpacaRouge" },
  { friendly: "Ampeg Opto Comp", internal: "HD2_CompressorOptoComp" },
  { friendly: "Arbitrator Fuzz", internal: "HD2_DistArbitratorFuzz" },
  { friendly: "Asheville Pattrn", internal: "HD2_FilterAshevillePattrn" },
  { friendly: "Auto Filter", internal: "HD2_FilterAutoFilter" },
  { friendly: "Autoswell", internal: "HD2_CompressorAutoSwell" },
  { friendly: "Ballistic Fuzz", internal: "HD2_DistBallisticFuzz" },
  { friendly: "Bighorn Fuzz", internal: "HD2_DistRamsHead" },
  { friendly: "Bitcrusher", internal: "HD2_DistBitcrusher" },
  { friendly: "Bleat Chop Trem", internal: "HD2_TremoloPattern" },
  { friendly: "Boctaver", internal: "VIC_PitchBoctaver" },
  { friendly: "Bubble Vibrato", internal: "HD2_VibratoBubbleVibrato" },
  { friendly: "Bucket Brigade", internal: "HD2_DelayBucketBrigade" },
  { friendly: "Cali Q Graphic", internal: "HD2_CaliQ" },
  { friendly: "Chorus", internal: "HD2_Chorus" },
  { friendly: "Chrome", internal: "HD2_WahChrome" },
  { friendly: "Chrome Custom", internal: "HD2_WahChromeCustom" },
  { friendly: "Clawthorn Drive", internal: "HD2_DistClawthornDrive" },
  { friendly: "Colorful", internal: "HD2_WahColorful" },
  { friendly: "Compulsive Drive", internal: "HD2_DistCompulsiveDrive" },
  { friendly: "Conductor", internal: "HD2_WahConductor" },
  { friendly: "Cosmos Echo", internal: "HD2_DelayCosmosEcho" },
  { friendly: "Courtesan Flange", internal: "HD2_FlangerCourtesanFlange" },
  { friendly: "Crisscross", internal: "HD2_DelayCrissCross" },
  { friendly: "Dark Dove Fuzz", internal: "HD2_DistDarkDoveFuzz" },
  { friendly: "Deez One Mod", internal: "HD2_DistDeezOneMod" },
  { friendly: "Deez One Vintage", internal: "HD2_DistDeezOneVintage" },
  { friendly: "Deluxe Comp", internal: "HD2_CompressorDeluxeComp" },
  { friendly: "Deluxe Phaser", internal: "HD2_PhaserDeluxePhaser" },
  { friendly: "Deranged Master", internal: "HD2_DistDerangedMaster" },
  { friendly: "Double Take", internal: "HD2_DelayDoubleDouble" },
  { friendly: "Double Tank", internal: "HD2_ReverbDoubleTank" },
  { friendly: "Dual Pitch", internal: "HD2_PitchDualPitch" },
  { friendly: "Ducked Delay", internal: "HD2_DelayDuckedDelay" },
  { friendly: "Dyhana Drive", internal: "HD2_DistDhyanaDrive" },
  { friendly: "Dynamic Ambience", internal: "VIC_ReverbDynAmbience" },
  { friendly: "Dynamic Bloom", internal: "VIC_ReverbDynBloom" },
  { friendly: "Dynamic Hall", internal: "VIC_ReverbRotating" },
  { friendly: "Dynamic Plate", internal: "VIC_DynPlate" },
  { friendly: "Dynamic Room", internal: "VIC_ReverbDynRoom" },
  { friendly: "Dynamix Flanger", internal: "HD2_FlangerDynamixFlanger" },
  { friendly: "Elephant Man", internal: "HD2_DelayElephantMan" },
  { friendly: "Euclidean Delay", internal: "Victoria_EuclideanDelay" },
  { friendly: "Fassel", internal: "HD2_WahFassel" },
  { friendly: "Feedbacker", internal: "VIC_FeedbackSim" },
  { friendly: "FlexoVibe", internal: "VIC_FlexoVibe" },
  { friendly: "Gain", internal: "HD2_VolPanGain" },
  { friendly: "Ganymede", internal: "HD2_ReverbGanymede" },
  { friendly: "Glitch Delay", internal: "VIC_DelayGlitch" },
  { friendly: "Glitz", internal: "HD2_ReverbGlitz" },
  { friendly: "Gray Flanger", internal: "HD2_FlangerGrayFlanger" },
  { friendly: "Hard Gate", internal: "HD2_GateHardGate" },
  { friendly: "Harmonic Flanger", internal: "HD2_FlangerHarmonicFlanger" },
  { friendly: "Harmonic Tremolo", internal: "HD2_TremoloHarmonic" },
  { friendly: "Hedgehog D9", internal: "HD2_DistHedgehogD9" },
  { friendly: "Heir Apparent", internal: "HD2_DistHeirApparent" },
  { friendly: "Heliosphere", internal: "HD2_DelayHeliosphere" },
  { friendly: "Horizon Drive", internal: "HD2_DistHorizonDrive" },
  { friendly: "Horizon Gate", internal: "HD2_GateHorizonGate" },
  { friendly: "Hot Springs", internal: "HD2_ReverbHxSpring" },
  { friendly: "IR 1024", internal: "HD2_ImpulseResponse1024" },
  { friendly: "IR 2048", internal: "HD2_ImpulseResponse2048" },
  { friendly: "Industrial Fuzz", internal: "HD2_DistIndustrialFuzz" },
  { friendly: "KWB", internal: "HD2_DistKWB" },
  { friendly: "Kinky Boost", internal: "HD2_DistKinkyBoost" },
  { friendly: "Kinky Comp", internal: "HD2_CompressorKinkyComp" },
  { friendly: "LA Studio Comp", internal: "HD2_CompressorLAStudioComp" },
  { friendly: "Legendary Drive", internal: "HD2_DistLegendaryDrive" },
  { friendly: "Low and High Cut", internal: "HD2_EQLowCutHighCut" },
  { friendly: "Low/High Shelf", internal: "HD2_EQLowShelfHighShelf" },
  { friendly: "Megaphone", internal: "HD2_DistMegaphone" },
  { friendly: "Minotaur", internal: "HD2_DistMinotaur" },
  { friendly: "Mod/Chorus Echo", internal: "HD2_DelayModChorusEcho" },
  { friendly: "Multi Pass", internal: "HD2_DelayMultiPass" },
  { friendly: "Mutant Filter", internal: "HD2_FilterMutantFilter" },
  { friendly: "Mystery Filter", internal: "HD2_FilterMysterFilter" },
  { friendly: "Noise Gate", internal: "HD2_GateNoiseGate" },
  { friendly: "Nonlinear", internal: "HD2_ReverbNonLinear" },
  { friendly: "Obsidian 7000", internal: "HD2_DistObsidian7000" },
  { friendly: "Optical Trem", internal: "HD2_TremoloOpticalTrem" },
  { friendly: "Parametric", internal: "HD2_EQParametric" },
  { friendly: "Pebble Phaser", internal: "HD2_PhaserPebblePhaser" },
  { friendly: "Pillars", internal: "HD2_DistPillars" },
  { friendly: "Pitch Echo", internal: "HD2_DelayPitch" },
  { friendly: "Pitch Wham", internal: "HD2_PitchPitchWham" },
  { friendly: "PlastiChorus", internal: "HD2_ChorusPlastiChorus" },
  { friendly: "Plateaux", internal: "HD2_ReverbPlateaux" },
  { friendly: "Pocket Fuzz", internal: "HD2_DistPocketFuzz" },
  { friendly: "Poly Capo", internal: "L6SPB_PolyDowntune" },
  { friendly: "Poly Detune", internal: "L6SPB_PolyChorus" },
  { friendly: "Poly Pitch", internal: "L6SPB_PolyPitch" },
  { friendly: "Poly Sustain", internal: "VIC_DelayPolySustain" },
  { friendly: "Poly Wham", internal: "L6SPB_PolyWham" },
  { friendly: "Prize Drive", internal: "HD2_DistPrizeDrive" },
  { friendly: "Ratatouille Dist", internal: "HD2_DistRatatouilleDist" },
  { friendly: "Ratchet", internal: "VIC_DelayRatchet" },
  { friendly: "Red Squeeze", internal: "HD2_CompressorRedSqueeze" },
  { friendly: "Regal Bass DI", internal: "HD2_DistRegalBassDI" },
  { friendly: "Retro Reel", internal: "HD2_RetroReel" },
  { friendly: "Reverse Delay", internal: "HD2_DelayReverseDelay" },
  { friendly: "Rochester Comp", internal: "HD2_CompressorRochesterComp" },
  { friendly: "Scream 808", internal: "HD2_DistScream808" },
  { friendly: "Script Mod Phase", internal: "HD2_PhaserScriptModPhase" },
  { friendly: "Searchlights", internal: "HD2_ReverbSearchlights" },
  { friendly: "Shimmer", internal: "VIC_ReverbShimmer" },
  { friendly: "Simple Delay", internal: "HD2_DelaySimpleDelay" },
  { friendly: "Simple EQ", internal: "HD2_EQSimple3Band" },
  { friendly: "Simple Pitch", internal: "HD2_PitchSimplePitch" },
  { friendly: "Simple Tilt", internal: "HD2_EQSimpleTilt" },
  { friendly: "Stupor OD", internal: "HD2_DistStuporOD" },
  { friendly: "Swedish Chainsaw", internal: "HD2_DistSwedishChainsaw" },
  { friendly: "Sweep Echo", internal: "HD2_DelaySweepEcho" },
  { friendly: "Teardrop 310", internal: "HD2_WahTeardrop310" },
  { friendly: "Teardrop Bass Q", internal: "HD2_WahTeardropBassQ" },
  { friendly: "Teemah!", internal: "HD2_DistTeemah" },
  { friendly: "Tesselator", internal: "VIC_DelayStutterEdit" },
  { friendly: "Thrifter Fuzz", internal: "HD2_DistThrifterFuzz" },
  { friendly: "Throaty", internal: "HD2_WahThroaty" },
  { friendly: "Tone Sovereign", internal: "HD2_DistToneSovereign" },
  { friendly: "Top Secret OD", internal: "HD2_DistTopSecretOD" },
  { friendly: "Transistor Tape", internal: "HD2_DelayTransistorTape" },
  { friendly: "Tremolo", internal: "HD2_TremoloTremolo" },
  { friendly: "Triangle Fuzz", internal: "HD2_DistTriangleFuzz" },
  { friendly: "Twin Harmony", internal: "HD2_PitchTwinHarmony" },
  { friendly: "Tycoctavia Fuzz", internal: "HD2_DistTycoctaviaFuzz" },
  { friendly: "UK Wah 846", internal: "HD2_WahUKWah846" },
  { friendly: "Ubiquitous Vibe", internal: "HD2_PhaserUbiquitousVibe" },
  { friendly: "Valve Driver", internal: "HD2_DistValveDriver" },
  { friendly: "Vermin Dist", internal: "HD2_DistVerminDist" },
  { friendly: "Vetta Wah", internal: "HD2_WahVettaWah" },
  { friendly: "Vintage Digital", internal: "HD2_DelayVintageDigitalV2" },
  { friendly: "Vintage Swell", internal: "HD2_DelaySwellVintageDigital" },
  { friendly: "Vital Boost", internal: "HD2_DistVitalBoost" },
  { friendly: "Vital Dist", internal: "HD2_DistVitalDist" },
  { friendly: "Volume", internal: "HD2_VolPanVol" },
  { friendly: "Weeper", internal: "HD2_WahWeeper" },
  { friendly: "Wringer Fuzz", internal: "HD2_DistWringerFuzz" },
  { friendly: "Xenomorph Fuzz", internal: "HD2_DistXenomorphFuzz" }
];

export const getEffectByInternal = (internal: string): EffectMapping | undefined => {
  return effectsMapping.find(effect => effect.internal === internal);
};

export const getEffectByFriendly = (friendly: string): EffectMapping | undefined => {
  return effectsMapping.find(effect => effect.friendly === friendly);
};
